export const assets = {
  logo: '/src/assets/modern-electricals-logo.png',
  heroShowroom: '/src/assets/hero-modern-electrical-showroom.jpg',
  aboutTeam: '/src/assets/about-modern-electricals-team.jpg',
  productsHero: '/src/assets/products-electrical-catalogue.jpg',
  servicesHero: '/src/assets/services-industrial-electrical.jpg',
  brandsHero: '/src/assets/brands-electrical-partners.jpg',
  projectsHero: '/src/assets/projects-commercial-installation.jpg',
  galleryHero: '/src/assets/gallery-modern-store.jpg',
  blogHero: '/src/assets/blog-electrical-insights.jpg',
  faqsHero: '/src/assets/faqs-customer-support.jpg',
  contactHero: '/src/assets/contact-kisumu-store.jpg',
  ledPanel: '/src/assets/product-led-panel-lighting.jpg',
  switchgear: '/src/assets/product-industrial-switchgear.jpg',
  solarKit: '/src/assets/product-hybrid-solar-inverter-kit.jpg',
  cables: '/src/assets/product-premium-cables-conduits.jpg',
  serviceSupply: '/src/assets/service-electrical-supply.jpg',
  serviceCommercial: '/src/assets/service-commercial-projects.jpg',
  serviceIndustrial: '/src/assets/service-industrial-supply.jpg',
  serviceSolar: '/src/assets/service-solar-solutions.jpg',
  serviceBulk: '/src/assets/service-bulk-orders.jpg',
  serviceConsultation: '/src/assets/service-consultation-delivery.jpg',
  galleryStore: '/src/assets/gallery-store-photos.jpg',
  galleryProducts: '/src/assets/gallery-product-displays.jpg',
  galleryProjects: '/src/assets/gallery-project-installations.jpg',
};
