import React, { createContext, useContext, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { Helmet, HelmetProvider } from 'react-helmet-async';
import { AnimatePresence, motion } from 'framer-motion';
import { CalendarDays, Check, Coffee, Heart, Camera, Mail, MapPin, Menu as MenuIcon, Minus, Moon, Palette, Phone, Plus, Search, ShoppingBag, Sparkles, Star, Sun, Trash2, Users, X } from 'lucide-react';
import { businessConfig } from './config/business';
import menuData from './data/menu.json';
import eventsData from './data/events.json';
import galleryData from './data/gallery.json';
import testimonials from './data/testimonials.json';
import coffee from './assets/images/coffee.svg';
import food from './assets/images/food-photo.svg';
import dessert from './assets/images/dessert.svg';
import kids from './assets/images/kids-event.svg';
import gallery1 from './assets/images/gallery-1.svg';
import gallery2 from './assets/images/gallery-2.svg';
import gallery3 from './assets/images/gallery-3.svg';
import gallery4 from './assets/images/gallery-4.svg';
import './styles.css';

type MenuItem = { id:string; name:string; description:string; price:number; category:string; image:string; available:boolean; bestSeller?:boolean };
type EventItem = { id:string; theme:string; description:string; ageGroup:string; date:string; time:string; instructor:string; venue:string; seats:number; price:number; poster:string };
type CartItem = MenuItem & { quantity:number };
const images: Record<string,string> = { coffee, food, dessert, kids, gallery1, gallery2, gallery3, gallery4 };
const money = (value:number) => `${businessConfig.currency} ${value.toLocaleString()}`;
const waLink = (message:string) => `https://wa.me/${businessConfig.whatsappNumber}?text=${encodeURIComponent(message)}`;

const CartContext = createContext<{items:CartItem[]; count:number; total:number; add:(i:MenuItem)=>void; inc:(id:string)=>void; dec:(id:string)=>void; remove:(id:string)=>void; clear:()=>void} | null>(null);
function useCart(){ const ctx = useContext(CartContext); if(!ctx) throw new Error('CartProvider missing'); return ctx; }
function CartProvider({children}:{children:React.ReactNode}){ const [items,setItems]=useState<CartItem[]>([]); const api=useMemo(()=>({items,count:items.reduce((s,i)=>s+i.quantity,0),total:items.reduce((s,i)=>s+i.quantity*i.price,0),add:(item:MenuItem)=>setItems(x=>x.some(i=>i.id===item.id)?x.map(i=>i.id===item.id?{...i,quantity:i.quantity+1}:i):[...x,{...item,quantity:1}]),inc:(id:string)=>setItems(x=>x.map(i=>i.id===id?{...i,quantity:i.quantity+1}:i)),dec:(id:string)=>setItems(x=>x.flatMap(i=>i.id===id&&i.quantity===1?[]:i.id===id?[{...i,quantity:i.quantity-1}]:[i])),remove:(id:string)=>setItems(x=>x.filter(i=>i.id!==id)),clear:()=>setItems([])}),[items]); return <CartContext.Provider value={api}>{children}</CartContext.Provider>; }
function ThemeProvider({children}:{children:React.ReactNode}){ const [dark,setDark]=useState(localStorage.theme==='dark'); React.useEffect(()=>{document.documentElement.classList.toggle('dark',dark); localStorage.theme=dark?'dark':'light'},[dark]); return <div><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button>{children}</div>; }
function Seo({title, description}:{title:string; description:string}){ return <Helmet><title>{title} | {businessConfig.name}</title><meta name="description" content={description}/></Helmet>; }
function Layout(){ const [open,setOpen]=useState(false); const {count}=useCart(); const nav=['Home','Menu','Kids Art Events','Reservations','Gallery','About','Contact']; return <><header className="nav"><Link to="/" className="brand"><img src={businessConfig.logo}/><span>{businessConfig.name}</span></Link><nav className="desktop">{nav.map(n=><NavLink to={n==='Home'?'/':'/'+n.toLowerCase().replaceAll(' ','-')}>{n}</NavLink>)}</nav><Link className="cartButton" to="/cart"><ShoppingBag/> <b>{count}</b></Link><Link className="primary" to="/checkout">Order Now</Link><button className="hamb" onClick={()=>setOpen(true)}><MenuIcon/></button></header>{open&&<aside className="drawer"><button onClick={()=>setOpen(false)}><X/></button>{nav.map(n=><NavLink onClick={()=>setOpen(false)} to={n==='Home'?'/':'/'+n.toLowerCase().replaceAll(' ','-')}>{n}</NavLink>)}<Link className="primary" to="/kids-art-events">Book Event</Link></aside>}<main><AnimatedRoutes/></main><Footer/></>; }
function AnimatedRoutes(){ const location=useLocation(); return <AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}><Routes location={location}><Route path="/" element={<Home/>}/><Route path="/menu" element={<MenuPage/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/kids-art-events" element={<Events/>}/><Route path="/reservations" element={<Reservations/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></motion.div></AnimatePresence>; }
function Hero(){ return <section className="hero"><div><p className="pill"><Sparkles/> Premium family café</p><h1>Artisan coffee, fresh meals, desserts & creative kids events.</h1><p>{businessConfig.tagline}. Order by WhatsApp, reserve a table, or book a children’s art session in one polished experience.</p><Link className="primary" to="/menu">Explore Menu</Link><Link className="ghost" to="/kids-art-events">Book Art Event</Link></div><img src={coffee}/></section>; }
function Home(){ const best=(menuData as MenuItem[]).filter(i=>i.bestSeller); return <><Seo title="Home" description="Premium café ordering and children art event booking."/><Hero/><Stats/><Section title="Best sellers"><CardGrid items={best}/></Section><Section title="Upcoming kids art events"><EventGrid/></Section><Section title="Gallery preview"><GalleryGrid limit={4}/></Section><Section title="Customer testimonials"><div className="cards">{testimonials.map(t=><article className="card"><Star/><p>“{t.quote}”</p><b>{t.name}</b></article>)}</div></Section><Newsletter/></>; }
function Stats(){ return <div className="stats">{['Artisan coffee','Fresh kitchen','Kids art studio','WhatsApp ordering'].map((s,i)=><article><b>{['4.9★','12','3','1-click'][i]}</b><span>{s}</span></article>)}</div>; }
function Section({title,children}:{title:string;children:React.ReactNode}){ return <section className="section"><h2>{title}</h2>{children}</section>; }
function CardGrid({items}:{items:MenuItem[]}){ return <div className="grid">{items.map(i=><MenuCard item={i}/>)}</div>; }
function MenuCard({item}:{item:MenuItem}){ const cart=useCart(); return <article className="menuCard"><img loading="lazy" src={images[item.image]}/><div><small>{item.category} · {item.available?'Available':'Sold out'}</small><h3>{item.name}</h3><p>{item.description}</p><footer><b>{money(item.price)}</b><button aria-label={`Favorite ${item.name}`}><Heart/></button><button disabled={!item.available} onClick={()=>cart.add(item)}><Plus/> Add</button></footer></div></article>; }
function MenuPage(){ const [q,setQ]=useState(''),[cat,setCat]=useState('All'),[sort,setSort]=useState('featured'); const items=[...(menuData as MenuItem[])].filter(i=>(cat==='All'||i.category===cat)&&i.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='price'?a.price-b.price:a.name.localeCompare(b.name)); const cats=['All',...new Set((menuData as MenuItem[]).map(i=>i.category))]; return <><Seo title="Menu" description="Search, filter and order Little Polo Café menu items."/><div className="toolbar"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search coffee, breakfast, dessert..."/><select onChange={e=>setSort(e.target.value)}><option value="featured">A-Z</option><option value="price">Price</option></select></div><div className="chips">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)}>{c}</button>)}</div><CardGrid items={items}/></>; }
function Cart(){ const c=useCart(); return <><Seo title="Cart" description="Review your café cart."/><Section title="Shopping cart">{c.items.length===0?<Empty text="Your cart is empty."/>:c.items.map(i=><div className="line"><img src={images[i.image]}/><b>{i.name}</b><button onClick={()=>c.dec(i.id)}><Minus/></button><span>{i.quantity}</span><button onClick={()=>c.inc(i.id)}><Plus/></button><strong>{money(i.price*i.quantity)}</strong><button onClick={()=>c.remove(i.id)}><Trash2/></button></div>)}<div className="total">Total <b>{money(c.total)}</b></div><Link className="primary" to="/checkout">Proceed to Checkout</Link><button className="ghost darktext" onClick={c.clear}>Clear cart</button></Section></>; }
function Checkout(){ const c=useCart(); const [type,setType]=useState('Take Away'); const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.currentTarget)); const lines=c.items.map(i=>`• ${i.quantity} x ${i.name} — ${money(i.price*i.quantity)}`).join('\n'); window.open(waLink(`Hello ${businessConfig.name}, I would like to place an order.\nName: ${d.name}\nPhone: ${d.phone}\nOrder type: ${type}\nAddress: ${d.address||'N/A'}\nPayment: ${d.payment}\nItems:\n${lines}\nInstructions: ${d.notes||'None'}\nGrand Total: ${money(c.total)}\nThank you.`),'_blank');}; return <FormPage title="Checkout" onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="phone" required placeholder="Phone number"/><input name="email" type="email" placeholder="Email optional"/><select onChange={e=>setType(e.target.value)}><option>Dine In</option><option>Take Away</option><option>Delivery</option></select>{type==='Delivery'&&<><input name="address" placeholder="Delivery address"/><input name="map" placeholder="Optional Google Maps link"/></>}<select name="payment"><option>Cash</option><option>M-Pesa</option><option>Card</option></select><textarea name="notes" placeholder="Special instructions"/><div className="total">Order Summary <b>{money(c.total)}</b></div><button className="primary">Place Order on WhatsApp</button></FormPage>; }
function Events(){ return <><Seo title="Kids Art Events" description="Book creative art events for children."/><Section title="Kids Art Events"><EventGrid/></Section><BookingForm/></>; }
function EventGrid(){ return <div className="grid">{(eventsData as EventItem[]).map(e=><article className="event"><img src={kids}/><h3>{e.theme}</h3><p>{e.description}</p><p><CalendarDays/> {e.date} · {e.time}</p><p><Users/> {e.ageGroup} · {e.seats} seats</p><b>{money(e.price)}</b><a className="primary" href="#booking">Book Now</a></article>)}</div>; }
function BookingForm(){ const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.currentTarget)); window.open(waLink(`Hello ${businessConfig.name}, I want to book an art event.\nParent: ${d.parent}\nPhone: ${d.phone}\nChild: ${d.child}, Age ${d.age}\nChildren: ${d.count}\nNotes: ${d.notes||'None'}`),'_blank')}; return <FormPage id="booking" title="Art Event Booking" onSubmit={submit}><input name="parent" required placeholder="Parent name"/><input name="phone" required placeholder="Phone"/><input name="email" type="email" placeholder="Email"/><input name="child" required placeholder="Child name"/><input name="age" required placeholder="Child age"/><input name="count" type="number" min="1" defaultValue="1"/><textarea name="notes" placeholder="Special notes"/><button className="primary">Send Booking</button></FormPage>; }
function Reservations(){ const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault(); const d=Object.fromEntries(new FormData(e.currentTarget)); window.open(waLink(`Reservation request for ${businessConfig.name}\nName: ${d.name}\nPhone: ${d.phone}\nDate: ${d.date}\nTime: ${d.time}\nGuests: ${d.guests}\nPreference: ${d.pref}\nRequests: ${d.notes||'None'}`),'_blank')}; return <FormPage title="Reservations" onSubmit={submit}><input name="name" required placeholder="Customer name"/><input name="phone" required placeholder="Phone"/><input name="date" type="date" required/><input name="time" type="time" required/><input name="guests" type="number" min="1" required/><select name="pref"><option>Indoor</option><option>Outdoor</option></select><textarea name="notes" placeholder="Special requests"/><button className="primary">Reserve via WhatsApp</button></FormPage>; }
function Gallery(){ return <><Seo title="Gallery" description="Coffee, food and kids event gallery."/><Section title="Premium Gallery"><GalleryGrid/></Section></>; }
function GalleryGrid({limit}:{limit?:number}){ return <div className="masonry">{galleryData.slice(0,limit).map(g=><figure><img loading="lazy" src={images[g.image]}/><figcaption>{g.title}</figcaption></figure>)}</div>; }
function About(){ return <><Seo title="About" description="The Little Polo Café story."/><section className="story"><h1>Our Story</h1><p>Little Polo Café was created as a warm third place for families: excellent coffee for grown-ups, thoughtful meals for everyone, and creative art experiences for children.</p>{['Mission','Vision','Quality Promise','Why Families Love Us','Kids Art Program'].map(x=><article><Check/><h3>{x}</h3><p>We combine hospitality, safe spaces, fresh ingredients and memorable design.</p></article>)}</section></>; }
function Contact(){ return <><Seo title="Contact" description="Contact Little Polo Café."/><section className="contact"><div className="map">Google Maps Placeholder</div><h1>Visit us</h1><p><MapPin/> {businessConfig.address}</p><p><Phone/> {businessConfig.phone}</p><p><Mail/> {businessConfig.email}</p><a className="primary" href={waLink('Hello Little Polo Café')}>WhatsApp</a><a className="ghost darktext" href={businessConfig.mapsLink}>Directions</a></section></>; }
function FormPage({title,onSubmit,children,id}:{title:string;onSubmit:(e:React.FormEvent<HTMLFormElement>)=>void;children:React.ReactNode;id?:string}){ return <><Seo title={title} description={`${title} at Little Polo Café.`}/><form id={id} className="form" onSubmit={onSubmit}><h1>{title}</h1>{children}</form></>; }
function Empty({text}:{text:string}){ return <div className="empty"><Coffee/><p>{text}</p><Link to="/menu">Continue shopping</Link></div>; }
function Newsletter(){ return <section className="newsletter"><h2>Join the Little Polo list</h2><p>Seasonal drinks, kids art calendars and family offers.</p><input placeholder="Email address"/><button>Subscribe</button></section>; }
function Footer(){ return <footer><img src={businessConfig.logo}/><b>{businessConfig.name}</b><p>{businessConfig.address}</p><p>{businessConfig.hours.map(h=>`${h.day}: ${h.time}`).join(' · ')}</p><a>Privacy Policy</a><a>Terms & Conditions</a><Camera/></footer>; }
function NotFound(){ return <section className="empty"><h1>404</h1><p>This page is not on the menu.</p><Link to="/">Return home</Link></section>; }
function App(){ return <HelmetProvider><CartProvider><ThemeProvider><BrowserRouter><Layout/></BrowserRouter></ThemeProvider></CartProvider></HelmetProvider>; }

createRoot(document.getElementById('root')!).render(<App/>);
