import React, {lazy, Suspense, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, NavLink, Route, Routes, useLocation} from 'react-router-dom';
import {Helmet, HelmetProvider} from 'react-helmet-async';
import {motion, AnimatePresence} from 'framer-motion';
import {useForm} from 'react-hook-form';
import useEmblaCarousel from 'embla-carousel-react';
import {ArrowRight, Award, Building2, Check, ChevronDown, Clock, Mail, MapPin, Menu, Moon, Phone, Search, Send, ShieldCheck, ShoppingBag, Sparkles, Sun, X, Zap} from 'lucide-react';
import './styles.css';

type Product={id:string;name:string;cat:string;image:string;specs:string[];apps:string[]};
type Service={slug:string;title:string;desc:string;image:string;benefits:string[]};
const img=(q:string)=>`https://images.unsplash.com/${q}?auto=format&fit=crop&w=1600&q=80`;
const hero=img('photo-1497366754035-f200968a6e72');
const products:Product[]=[
{id:'led-panel-lighting',name:'Architectural LED Panel Lighting',cat:'Lighting',image:img('photo-1513506003901-1e6a229e2d15'),specs:['18W–60W options','CRI 90+','3 year warranty'],apps:['Offices','Showrooms','Luxury homes']},
{id:'industrial-switchgear',name:'Industrial Switchgear & Protection',cat:'Industrial',image:img('photo-1581092921461-eab62e97a780'),specs:['IEC compliant','Modular breakers','Surge protection'],apps:['Factories','Warehouses','Plant rooms']},
{id:'solar-inverter-kit',name:'Hybrid Solar Inverter Kit',cat:'Solar',image:img('photo-1509391366360-2e959784a276'),specs:['3kW–10kW','MPPT charging','Battery ready'],apps:['Homes','SMEs','Remote sites']},
{id:'cables-conduits',name:'Premium Cables & Conduits',cat:'Wiring',image:img('photo-1621905251189-08b45d6a269e'),specs:['Copper core','Fire resistant','KEBS certified'],apps:['Contractors','Commercial builds','Renovations']}
];
const services:Service[]=[
{slug:'electrical-supply',title:'Electrical Supply',desc:'Curated premium electrical materials sourced for safety, durability and exact project fit.',image:img('photo-1504917595217-d4dc5ebe6122'),benefits:['Quality controlled stock','Competitive contractor pricing','Expert product guidance']},
{slug:'commercial-projects',title:'Commercial Projects',desc:'Reliable procurement support for offices, retail, hospitality and real-estate developments.',image:img('photo-1486406146926-c627a92ad1ab4'),benefits:['Bill of quantities support','Bulk scheduling','After-sales continuity']},
{slug:'industrial-supply',title:'Industrial Supply',desc:'Robust gear for factories, workshops and power rooms requiring dependable performance.',image:img('photo-1581092160607-ee22621dd758'),benefits:['Switchgear expertise','Safety-first selection','Fast replacement sourcing']},
{slug:'solar-solutions',title:'Solar Solutions',desc:'Solar panels, inverters, batteries and protection accessories for resilient clean power.',image:img('photo-1497440001374-f26997328c1b'),benefits:['Hybrid system bundles','Energy savings advice','Scalable components']},
{slug:'bulk-orders',title:'Bulk Orders',desc:'Streamlined purchasing for contractors and institutions with transparent communication.',image:img('photo-1586528116311-ad8dd3c8310d'),benefits:['Volume pricing','Delivery coordination','Dedicated account support']},
{slug:'consultation-delivery',title:'Consultation & Delivery',desc:'Professional advice, store directions and delivery across Kisumu and surrounding regions.',image:img('photo-1560250097-0b93528c311a'),benefits:['Responsive WhatsApp support','Site-aware recommendations','Timely fulfilment']}
];
const pages=['Home','About','Products','Services','Brands','Projects','Gallery','Blog','FAQs','Contact'];
function useTheme(){const [dark,setDark]=useState(()=>localStorage.theme==='dark');useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.theme=dark?'dark':'light'},[dark]);return{dark,setDark}}
function SEO({title,desc}:{title:string;desc:string}){return <Helmet><title>{title} | Modern Electricals</title><meta name="description" content={desc}/><script type="application/ld+json">{JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness',name:'Modern Electricals',address:'Kisumu, Kenya',telephone:'+254 700 000 000',areaServed:'Kenya'})}</script></Helmet>}
function Layout(){const {dark,setDark}=useTheme();const [open,setOpen]=useState(false);const [sc,setSc]=useState(false);useEffect(()=>{const f=()=>setSc(scrollY>24);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);return <><nav className={`nav ${sc?'shrink':''}`}><Link to="/" className="logo"><span>ME</span><b>Modern Electricals</b></Link><div className="menu">{pages.map(p=><NavLink key={p} to={p==='Home'?'/':'/'+p.toLowerCase()}>{p}</NavLink>)}</div><div className="actions"><Search size={20}/><button className="toggle" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button><a className="whats" href="https://wa.me/254700000000">WhatsApp</a><Link className="btn small" to="/contact">Request Quote</Link><button className="hamb" onClick={()=>setOpen(1 as never)}><Menu/></button></div></nav>{open&&<div className="mobile"><button onClick={()=>setOpen(false)}><X/></button>{pages.map(p=><Link onClick={()=>setOpen(false)} key={p} to={p==='Home'?'/':'/'+p.toLowerCase()}>{p}</Link>)}</div>}<main><AnimatedRoutes/></main><Footer/><Floaters/></>}
function AnimatedRoutes(){const loc=useLocation();return <AnimatePresence mode="wait"><motion.div key={loc.pathname} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.35}}><Routes location={loc}><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/products" element={<Products/>}/><Route path="/products/:id" element={<ProductDetail/>}/><Route path="/services" element={<Services/>}/><Route path="/services/:slug" element={<Services/>}/><Route path="/brands" element={<Brands/>}/><Route path="/projects" element={<Projects/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/blog" element={<Blog/>}/><Route path="/faqs" element={<Faqs/>}/><Route path="/contact" element={<Contact/>}/></Routes></motion.div></AnimatePresence>}
function Home(){return <><SEO title="Premium Electrical Supplier in Kisumu" desc="Quality electrical materials, lighting, industrial equipment and solar products."/><section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(0,0,0,.7),rgba(0,0,0,.15)),url(${hero})`}}><div className="particles"/>{[1,2,3].map(i=><span key={i} className={`orb o${i}`}/>)}<motion.div className="heroText" initial={{opacity:0,y:40}} animate={{opacity:1,y:0}}><p className="eyebrow"><Sparkles/> Premium Kisumu Electrical Supplier</p><h1>Powering Kenya With Quality Electrical Solutions</h1><p>Providing premium electrical materials, lighting systems, industrial equipment and solar products for homes, businesses and contractors.</p><div><Link className="btn" to="/products">Browse Products</Link><Link className="btn ghost" to="/contact">Request Quotation</Link><button className="play">Watch Company Profile</button></div></motion.div><div className="scroll">Scroll</div></section><Stats/><Section title="Signature Product Lines"><Carousel/></Section><Testimonials/></>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="section"><p className="eyebrow"><Zap/> Modern Electricals</p><h2>{title}</h2>{children}</section>}
function Stats(){return <div className="stats">{['15+ Years Trust','1,200+ Products','98% Repeat Clients','24hr Quote Response'].map((s,i)=><motion.div whileHover={{y:-6}} className="stat" key={s}><b>{s.split(' ')[0]}</b><span>{s.substring(s.indexOf(' ')+1)}</span></motion.div>)}</div>}
function Carousel(){const [ref]=useEmblaCarousel({loop:true});return <div className="embla" ref={ref}><div className="emblaInner">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></div>}
function ProductCard({p}:{p:Product}){return <Link className="card product" to={`/products/${p.id}`}><img src={p.image} loading="lazy"/><small>{p.cat}</small><h3>{p.name}</h3><p>{p.specs.join(' • ')}</p><span>View details <ArrowRight size={16}/></span></Link>}
function About(){return <><SEO title="About" desc="Company story, mission, vision and team."/><PageHero title="Built on trust, powered by expertise" image={img('photo-1552664730-d307ca884978')}/><Section title="Company Story"><div className="grid two"><Text title="Mission" text="To supply safe, premium and future-ready electrical solutions with uncompromising service."/><Text title="Vision" text="To be Western Kenya’s most trusted electrical supply partner for modern homes and ambitious projects."/></div></Section><Section title="Core Values & Timeline"><div className="timeline">{['Quality first','Honest advice','Fast fulfilment','Long-term partnerships'].map(x=><div><Check/> {x}</div>)}</div></Section><Team/></>}
function Text({title,text}:{title:string;text:string}){return <div className="glass"><h3>{title}</h3><p>{text}</p></div>}
function Products(){const [q,setQ]=useState('');const shown=products.filter(p=>(p.name+p.cat).toLowerCase().includes(q.toLowerCase()));return <><SEO title="Products" desc="Electrical product catalogue."/><PageHero title="Premium electrical catalogue" image={img('photo-1621905252507-b35492cc74b4')}/><section className="section"><input className="search" placeholder="Search products, categories, specifications..." onChange={e=>setQ(e.target.value)}/><div className="chips">{['All','Lighting','Industrial','Solar','Wiring'].map(c=><button>{c}</button>)}</div><div className="grid cards">{shown.map(p=><ProductCard p={p} key={p.id}/>)}</div></section></>}
function ProductDetail(){const id=location.pathname.split('/').pop();const p=products.find(x=>x.id===id)||products[0];return <><SEO title={p.name} desc={p.specs.join(', ')}/><PageHero title={p.name} image={p.image}/><section className="section grid two"><div><img className="round" src={p.image}/></div><div className="glass"><h2>Specifications</h2>{p.specs.map(s=><p><Check/> {s}</p>)}<h3>Applications</h3>{p.apps.map(s=><p>{s}</p>)}<a className="btn" href="/contact">Request Quote</a><a className="btn ghost" href="https://wa.me/254700000000">WhatsApp Inquiry</a></div></section><Section title="Related Products"><div className="grid cards">{products.filter(x=>x.id!==p.id).map(x=><ProductCard p={x}/>)}</div></Section></>}
function Services(){return <><SEO title="Services" desc="Electrical supply, commercial, industrial, solar, bulk and consultation services."/><PageHero title="Services engineered for reliable projects" image={img('photo-1581092580497-e0d23cbdf1dc')}/><div className="grid serviceGrid">{services.map(s=><Link className="service" to={`/services/${s.slug}`}><img src={s.image}/><div><h3>{s.title}</h3><p>{s.desc}</p>{s.benefits.map(b=><small><ShieldCheck size={14}/> {b}</small>)}</div></Link>)}</div></>}
function Brands(){return <><SEO title="Brands" desc="Trusted electrical brands supplied in Kisumu."/><PageHero title="Trusted brands. Genuine products." image={img('photo-1560472354-b33ff0c44a43')}/><section className="section brandGrid">{['Schneider Electric','Siemens','Philips','Legrand','ABB','Havells','Samsung','Tesla Energy'].map(b=><div className="brand"><Award/><h3>{b}</h3><p>Available product ranges, history and procurement support.</p></div>)}</section></>}
function Projects(){return <><SEO title="Projects" desc="Residential, commercial and industrial project showcase."/><PageHero title="Project showcase" image={img('photo-1494526585095-c41746248156')}/><Masonry items={['Residential wiring','Commercial fit-out','Industrial power room','Solar backup','Before & After','Luxury lighting']}/></>}
function Gallery(){return <><SEO title="Gallery" desc="Store, products, projects and customer gallery."/><PageHero title="Pinterest-style gallery" image={img('photo-1500530855697-b586d89ba3ee')}/><Masonry items={['Store photos','Lighting displays','Product shelves','Happy customers','Solar installs','Contractor pickups','Modern homes','Industrial panels']}/></>}
function Blog(){return <><SEO title="Blog" desc="Electrical insights and buying guides."/><PageHero title="Insights for safer, smarter power" image={img('photo-1497366811353-6870744d04b2')}/><section className="section grid cards">{['Choosing the right cable size','Why surge protection matters','Solar backup for Kisumu homes','Commercial lighting trends'].map(t=><article className="card"><small>Featured</small><h3>{t}</h3><p>Expert guidance from Modern Electricals with related posts and newsletter signup.</p></article>)}</section><Newsletter/></>}
function Faqs(){const [q,setQ]=useState('');const faqs=['Do you deliver in Kisumu?','Can contractors request bulk pricing?','Are products genuine and warrantied?','Do you provide solar consultations?'];return <><SEO title="FAQs" desc="Frequently asked questions."/><PageHero title="Popular questions" image={img('photo-1450101499163-c8848c66ca85')}/><section className="section"><input className="search" placeholder="Search FAQs" onChange={e=>setQ(e.target.value)}/>{faqs.filter(f=>f.toLowerCase().includes(q.toLowerCase())).map(f=><details className="faq"><summary>{f}<ChevronDown/></summary><p>Yes. Contact our team for precise, project-specific assistance and quotation support.</p></details>)}</section></>}
function Contact(){const {register,handleSubmit}=useForm();return <><SEO title="Contact" desc="Request quotations, directions and business hours."/><PageHero title="Let’s power your next project" image={img('photo-1521791136064-7986c2920216')}/><section className="section grid two"><form className="glass form" onSubmit={handleSubmit(()=>alert('Thank you. We will contact you shortly.'))}><input {...register('name')} placeholder="Name"/><input {...register('email')} placeholder="Email"/><input {...register('phone')} placeholder="Phone"/><textarea {...register('message')} placeholder="What do you need?"/><button className="btn"><Send/> Send Request</button></form><div className="glass"><h2>Modern Electricals, Kisumu</h2><p><MapPin/> Kisumu, Kenya</p><p><Phone/> +254 700 000 000</p><p><Mail/> sales@modernelectricals.co.ke</p><p><Clock/> Mon–Sat, 8:00–18:00</p><iframe title="Google Map" src="https://www.google.com/maps?q=Kisumu%20Kenya&output=embed"/></div></section></>}
function PageHero({title,image}:{title:string;image:string}){return <header className="pageHero" style={{backgroundImage:`linear-gradient(90deg,rgba(17,17,17,.75),rgba(215,38,56,.25)),url(${image})`}}><motion.h1 initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>{title}</motion.h1></header>}
function Team(){return <Section title="Meet the Team"><div className="grid cards">{['Managing Director','Procurement Lead','Project Advisor'].map(r=><div className="card"><div className="avatar"/><h3>{r}</h3><p>Professional, responsive and committed to customer trust.</p></div>)}</div></Section>}
function Testimonials(){return <Section title="Why Customers Trust Us"><div className="grid cards">{['Genuine products','Professional advice','Fast quotations'].map(t=><div className="card"><h3>{t}</h3><p>Modern Electricals combines premium stock with practical support for every scale of project.</p></div>)}</div></Section>}
function Masonry({items}:{items:string[]}){return <section className="masonry">{items.map((it,i)=><motion.div whileHover={{scale:1.02}} className="tile"><img src={img(['photo-1513506003901-1e6a229e2d15','photo-1621905251189-08b45d6a269e','photo-1509391366360-2e959784a276'][i%3])}/><b>{it}</b></motion.div>)}</section>}
function Newsletter(){return <section className="newsletter"><h2>Get product guides and offers</h2><input placeholder="Email address"/><button className="btn">Subscribe</button></section>}
function Footer(){return <footer><div><h2>Modern Electricals</h2><p>Premium electrical supplies for homes, businesses, contractors and industry in Kenya.</p></div><div>{pages.map(p=><Link to={p==='Home'?'/':'/'+p.toLowerCase()}>{p}</Link>)}</div><div><p>Products • Services • Newsletter • Social Media</p><iframe title="Footer map" src="https://www.google.com/maps?q=Kisumu%20Kenya&output=embed"/></div><small>© 2026 Modern Electricals. All rights reserved.</small></footer>}
function Floaters(){return <><a className="float whatsFloat" href="https://wa.me/254700000000">WhatsApp</a><button className="float top" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>↑</button><div className="cookie">We use cookies for a refined experience. <button>Accept</button></div></>}
function App(){return <HelmetProvider><BrowserRouter><Suspense fallback={<div className="loader">Modern Electricals</div>}><Layout/></Suspense></BrowserRouter></HelmetProvider>}
createRoot(document.getElementById('root')!).render(<App/>);
