import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Helmet, HelmetProvider} from 'react-helmet-async';
import {AnimatePresence, motion} from 'framer-motion';
import {Award, Bell, CalendarDays, Camera, Check, ChevronRight, Clock, Coffee, CreditCard, Heart, Home, MapPin, Menu, MessageCircle, Moon, PackageCheck, Palette, Phone, Search, ShoppingBag, Sparkles, Star, Sun, Truck, UserRound, Utensils, X} from 'lucide-react';
import './styles.css';

type Theme='light'|'dark';
type Tab='home'|'menu'|'art'|'orders'|'profile';
type MenuItem={name:string;category:string;price:string;image:string;description:string;options:string[];favorite?:boolean};
type EventItem={theme:string;date:string;time:string;age:string;seats:number;price:string;image:string;instructor:string;materials:string[]};
const img=(id:string)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;
const menuItems:MenuItem[]=[
{name:'Little Polo Latte',category:'Coffee',price:'KSh 320',image:img('photo-1461023058943-07fcbe16d735'),description:'Velvety espresso, steamed milk and caramel cloud foam.',options:['Oat milk','Extra shot','Vanilla syrup'],favorite:true},
{name:'Creamy Iced Mocha',category:'Iced Coffee',price:'KSh 380',image:img('photo-1517701604599-bb29b565090c'),description:'Chocolate espresso over ice with whipped cream.',options:['Less ice','Almond milk','Chocolate drizzle']},
{name:'Strawberry Dream Shake',category:'Milkshakes',price:'KSh 450',image:img('photo-1572490122747-3968b75cc699'),description:'Premium strawberry milkshake topped with sprinkles.',options:['No cream','Extra scoop','Kids cup'],favorite:true},
{name:'Ceremonial Matcha Cloud',category:'Matcha',price:'KSh 430',image:img('photo-1515823064-d6e0c04616a7'),description:'Earthy matcha with honey, milk and soft vanilla notes.',options:['Iced','Coconut milk','Honey-free']},
{name:'Mango Sunshine Smoothie',category:'Smoothies',price:'KSh 420',image:img('photo-1623065422902-30a2d299bbe4'),description:'Mango, banana and yoghurt blended until silky.',options:['Protein boost','No yoghurt','Chia seeds']},
{name:'Rainbow Kids Waffles',category:'Kids Menu',price:'KSh 520',image:img('photo-1562376552-0d160a2f238d'),description:'Mini waffles with fruit, chocolate dip and playful toppings.',options:['Nut-free','Extra fruit','Birthday candle']},
{name:'Lotus Cheesecake',category:'Desserts',price:'KSh 390',image:img('photo-1533134242443-d4fd215305ad'),description:'Creamy cheesecake with biscuit crumble and coffee caramel.',options:['Takeaway','Add berries','Add candle']},
{name:'Chicken Pesto Panini',category:'Sandwiches',price:'KSh 680',image:img('photo-1528735602780-2552fd46c7af'),description:'Toasted artisan bread, chicken, pesto and mozzarella.',options:['Extra cheese','No pesto','Side salad']}
];
const categories=['Coffee','Iced Coffee','Milkshakes','Matcha','Tea','Fresh Juice','Smoothies','Mocktails','Desserts','Sandwiches','Bites','Kids Menu'];
const events:EventItem[]=[
{theme:'Paint & Juice',date:'Sat, 8 Aug',time:'10:00 AM',age:'4–8 yrs',seats:9,price:'KSh 1,500',image:img('photo-1513364776144-60967b0f800f'),instructor:'Miss Achieng',materials:['Canvas','Apron','Juice box','Take-home art']},
{theme:'Family Art Day',date:'Sun, 16 Aug',time:'2:00 PM',age:'All ages',seats:14,price:'KSh 2,800',image:img('photo-1460661419201-fd4cecdf8a8b'),instructor:'Little Polo Studio',materials:['Family canvas','Snacks','Photo corner']},
{theme:'Holiday Art Camp',date:'Mon, 24 Aug',time:'9:00 AM',age:'6–12 yrs',seats:6,price:'KSh 4,500',image:img('photo-1493106819501-66d381c466f1'),instructor:'Creative Kids Team',materials:['Daily kits','Lunch','Certificate']}
];
const orderSteps=['Order received','Preparing','Ready','Out for delivery','Delivered'];
function useTheme(){const [theme,setTheme]=useState<Theme>(()=>(localStorage.theme as Theme)||'light');useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.theme=theme},[theme]);return{theme,setTheme}};
function App(){const {theme,setTheme}=useTheme();const [tab,setTab]=useState<Tab>('home');const [drawer,setDrawer]=useState(false);return <HelmetProvider><Helmet><title>Little Polo Café | Kisumu Coffee & Kids Art Club</title><meta name="description" content="Premium café ordering, Little Polo Art Club event booking, rewards, reservations and delivery tracking in Kisumu."/></Helmet><div className="app"><Header theme={theme} setTheme={setTheme} setDrawer={setDrawer}/><AnimatePresence mode="wait"><motion.main key={tab} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.28}}>{tab==='home'&&<HomeScreen setTab={setTab}/>} {tab==='menu'&&<MenuScreen/>} {tab==='art'&&<ArtClub/>} {tab==='orders'&&<Orders/>} {tab==='profile'&&<Profile/>}</motion.main></AnimatePresence><BottomNav tab={tab} setTab={setTab}/>{drawer&&<AdminDrawer setDrawer={setDrawer}/>}</div></HelmetProvider>}
function Header({theme,setTheme,setDrawer}:{theme:Theme;setTheme:(t:Theme)=>void;setDrawer:(v:boolean)=>void}){return <header className="topbar"><button className="icon" onClick={()=>setDrawer(true)} aria-label="Open admin dashboard"><Menu/></button><div><p className="micro">A Little Piece of Heaven</p><h1>Little Polo Café</h1></div><button className="icon" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Toggle theme">{theme==='light'?<Moon/>:<Sun/>}</button></header>}
function HomeScreen({setTab}:{setTab:(t:Tab)=>void}){return <><section className="heroCard"><div><p className="pill"><Sparkles size={16}/> Kisumu's warm family café</p><h2>Coffee, sweet bites & magical kids art days.</h2><p>Order your favourite latte, book a child into Little Polo Art Club, earn rewards and track delivery from one beautiful app.</p><div className="heroActions"><button onClick={()=>setTab('menu')}>Quick order <ChevronRight size={18}/></button><button onClick={()=>setTab('art')} className="secondary">Book event</button></div></div><img src={img('photo-1509042239860-f550ce710b93')} alt="Premium coffee"/></section><Stats/><Section title="Today’s specials" action="View menu"><Horizontal items={menuItems.slice(0,4)}/></Section><Section title="Upcoming art events" action="Book seats"><div className="eventMini">{events.map(e=><EventCard event={e} compact key={e.theme}/>)}</div></Section><section className="promo"><div><p className="micro">Loyalty preview</p><h3>1,240 points</h3><p>Only 260 points away from a free milkshake.</p></div><Award/><button>Redeem rewards</button></section><Community/></>}
function Stats(){return <div className="stats">{[['12 min','pickup'],['4.9★','parents'],['32','seats left'],['KSh 0','delivery deal']].map(([a,b])=><div><b>{a}</b><span>{b}</span></div>)}</div>}
function Section({title,action,children}:{title:string;action?:string;children:React.ReactNode}){return <section className="section"><div className="sectionHead"><h2>{title}</h2>{action&&<a>{action}</a>}</div>{children}</section>}
function Horizontal({items}:{items:MenuItem[]}){return <div className="rail">{items.map(item=><MenuCard item={item} key={item.name}/>)}</div>}
function MenuScreen(){const [active,setActive]=useState('Coffee');const items=useMemo(()=>menuItems.filter(i=>i.category===active||active==='All'),[active]);return <><SearchPanel/><div className="chips"><button onClick={()=>setActive('All')} className={active==='All'?'active':''}>All</button>{categories.map(c=><button onClick={()=>setActive(c)} className={active===c?'active':''}>{c}</button>)}</div><Section title={`${active} menu`}><div className="grid">{items.map(item=><MenuCard item={item} wide key={item.name}/>)}</div></Section></>}
function SearchPanel(){return <div className="searchPanel"><Search/><input placeholder="Search coffee, desserts, mocktails..."/><button><ShoppingBag size={18}/> Cart</button></div>}
function MenuCard({item,wide}:{item:MenuItem;wide?:boolean}){return <article className={`menuCard ${wide?'wide':''}`}><img src={item.image} alt={item.name}/><div><div className="cardTop"><span>{item.category}</span><button aria-label="Favorite"><Heart fill={item.favorite?'currentColor':'none'}/></button></div><h3>{item.name}</h3><p>{item.description}</p><small>Customize: {item.options.join(' • ')}</small><div className="buy"><b>{item.price}</b><button>Add to cart</button></div></div></article>}
function ArtClub(){return <><section className="artHero"><Palette/><h2>Little Polo Art Club</h2><p>Register children, select age groups, book multiple seats, pay online and add reminders to your phone calendar.</p></section><Section title="Upcoming creative experiences"><div className="grid">{events.map(e=><EventCard event={e} key={e.theme}/>)}</div></Section><Section title="Event gallery"><div className="gallery">{['photo-1541961017774-22349e4a1262','photo-1503454537195-1dcabb73ffb9','photo-1513475382585-d06e58bcb0e0','photo-1516627145497-ae6968895b74'].map(x=><img src={img(x)} alt="Kids artwork gallery"/>)}</div></Section></>}
function EventCard({event,compact}:{event:EventItem;compact?:boolean}){return <article className={`eventCard ${compact?'compact':''}`}><img src={event.image} alt={event.theme}/><div><p className="pill">{event.seats} seats remaining</p><h3>{event.theme}</h3><p><CalendarDays size={16}/> {event.date} • {event.time}</p><p><UserRound size={16}/> {event.age} • {event.instructor}</p><small>Materials included: {event.materials.join(', ')}</small><div className="buy"><b>{event.price}</b><button>Register child</button></div></div></article>}
function Orders(){return <><Section title="Live delivery tracking"><div className="tracker">{orderSteps.map((s,i)=><div className={i<3?'done':''}><Check/><span>{s}</span></div>)}</div></Section><Section title="Reorder previous favourites"><Horizontal items={menuItems.slice(2,6)}/></Section><section className="reservation"><h2>Reservations & private events</h2><p>Reserve tables, birthday parties, family gatherings, art sessions and private events with date, time, guests and special requests.</p><button>Reserve now</button></section></>}
function Profile(){return <><section className="profile"><div className="avatar">LP</div><h2>Grace Wanjala</h2><p>Gold member • Birthday rewards active</p></section><div className="settings">{['Personal details','Addresses','Saved cards','Favourite items','Event bookings','Order history','Notification preferences','WhatsApp, phone, email & maps'].map((x,i)=><div><span>{[UserRound,MapPin,CreditCard,Heart,Palette,PackageCheck,Bell,Phone].map(Icon=><Icon/>)[i]}</span><b>{x}</b><ChevronRight/></div>)}</div></>}
function Community(){return <Section title="Community feed"><div className="feed">{['New honey cinnamon latte is here','Weekend Kids Club artwork highlights','Parent testimonial: perfect birthday art party'].map((p,i)=><article><img src={img(['photo-1554118811-1e0d58224f24','photo-1513364776144-60967b0f800f','photo-1529156069898-49953e39b3ac'][i])}/><h3>{p}</h3><p><Heart size={16}/> Like · <MessageCircle size={16}/> Comment · Share</p></article>)}</div></Section>}
function AdminDrawer({setDrawer}:{setDrawer:(v:boolean)=>void}){return <aside className="drawer"><button className="close" onClick={()=>setDrawer(false)}><X/></button><h2>Admin Dashboard</h2><p>Manage Little Polo Café operations.</p>{['Menu items & prices','Orders & deliveries','Create art events','Bookings & QR tickets','Upload event photos','Customer analytics','Loyalty rewards','Promotional notifications','Reports'].map(x=><div className="adminRow"><Check/> {x}</div>)}<div className="payments"><h3>Payments</h3><p>M-Pesa • Visa • Mastercard • Airtel Money • Cash on Pickup</p></div></aside>}
function BottomNav({tab,setTab}:{tab:Tab;setTab:(t:Tab)=>void}){const nav:Array<[Tab,React.ElementType,string]>=[['home',Home,'Home'],['menu',Utensils,'Menu'],['art',Palette,'Art Club'],['orders',Truck,'Orders'],['profile',UserRound,'Profile']];return <nav className="bottomNav">{nav.map(([id,Icon,label])=><button onClick={()=>setTab(id)} className={tab===id?'active':''}><Icon/><span>{label}</span></button>)}</nav>}

createRoot(document.getElementById('root')!).render(<App/>);
